#pragma once

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM_PER_KEY

#define ACHORDION_STREAK

#define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_LED_SYNC

#define RGB_MATRIX_KEYPRESSES
