MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
RAW_ENABLE = yes

SRC += features/achordion.c
CFLAGS += -Wno-error=cpp
LTO_ENABLE = yes
