#pragma once

#define ONESHOT_TIMEOUT 5000
#define ONESHOT_TAP_TOGGLE 0

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_LED_SYNC

#define RGB_MATRIX_KEYPRESSES
